#!/bin/bash

${HADOOP_HOME?"HADOOP_HOME not initialized. Check .bashrc file"} 2>/dev/null

# cat ${HADOOP_HOME}/etc/hadoop/slaves | grep -v ^# | xargs -i ssh {} $1

for i in `cat ${HADOOP_HOME}/etc/hadoop/slaves`
do
	echo "Run command $1 in $i "
	ssh $i $1
	echo "================================="
done


